#**Project Title**

Customer Banking and Financial Analytics

#**Objective(Problem statment)**

1. To analyze customer banking and financial data to identify meaningful patterns, trends, and insights using exploratory data analysis (EDA).

2. To understand customer demographics, account information, transaction behavior, loan details, and credit card activity.

3. To examine customer feedback and resolution status to understand customer service experience.

4. To clean, transform, and preprocess the selected data to make it suitable for analysis and visualization.

5. To create meaningful visualizations and dashboards using Python and Power BI to support data-driven decision-making.

6. To provide actionable insights and recommendations based on the analysis.

#**Outcome**

The project delivers a comprehensive view of customer banking and financial activity by uncovering meaningful patterns across customer profiles, account balances, transactions, loans, credit card usage, and customer feedback.

Through Python-based data analysis and an interactive Power BI dashboard, the project transforms raw banking data into actionable business insights, enabling stakeholders to understand customer behavior, identify financial trends, evaluate service performance, and support informed, data-driven decision-making.

#**Domain**

Banking and Financial Services

#**Dataset Information**

**Source:** https://github.com/ahsan084/Banking-Dataset/blob/main/Comprehensive_Banking_Database.csv

**Original Dataset Size:** 5,000 rows × 40 columns

**Dataset Used for Analysis:** 5,000 rows × 18 selected columns

**Year / Timeline:** The dataset covers the period from 2000 to 2023. Account opening records span from 2000 to 2022, while transaction, credit card, payment, and customer feedback activities are primarily recorded during 2023.

**Format:** CSV

**Dataset Column/features Description:**

* **Age** - Age of the customer.

* **Gender** - Gender of the customer.

* **City** - City associated with the customer.

* **Account Type** - Type of bank account held by the customer.

* **Account Balance** - Current balance maintained in the customer's bank account.

* **Date Of Account Opening** - Date on which the customer's bank account was opened.

* **Transaction Date** - Date on which the banking transaction occurred.

* **Transaction Type** - Type or category of banking transaction.

* **Transaction Amount** - Monetary amount involved in the transaction.

* **Loan Type** - Type of loan associated with the customer.

* **Loan Amount** - Monetary amount associated with the customer's loan.

* **Interest Rate** - Interest rate applicable to the customer's loan.

* **Loan Status** - Current status of the loan, such as approval or rejection status.

* **Card Type** - Type of credit card held by the customer.

* **Credit Limit** - Maximum credit limit available on the customer's credit card.

* **Credit Card Balance** - Outstanding balance on the customer's credit card.

* **Feedback Type** - Category or type of feedback provided by the customer.

* **Resolution Status** - Status indicating whether the customer's feedback or issue has been resolved.

#Stages for DA Project

##Stage 1 – Problem Definition and Dataset Selection

* **Business Problem and Expected Outcome**

The objective is to analyze customer banking and financial data to understand customer profiles, account activity, transaction behavior, loan performance, credit card usage, and customer feedback.

The analysis will help identify meaningful patterns and trends in customer financial activity, understand banking and credit-related behavior, and evaluate customer feedback and resolution patterns. The findings will be used to generate actionable insights and support data-driven decision-making through Python analysis and an interactive Power BI dashboard.

* **Dataset Selection**

The Customer Banking Dataset is selected for this project. It contains 5,000 customer records with 40 features covering customer demographics, account information, transactions, loans, credit cards, and customer feedback.

For this analysis, 18 relevant features will be selected from the original 40 columns based on the project objectives. The selected working dataset will contain 5,000 records and 18 analytical columns, covering customer demographics, account details, transaction activity, loan information, credit card usage, and customer feedback.

* **Source:** https://github.com/ahsan084/Banking-Dataset/blob/main/Comprehensive_Banking_Database.csv

#**Inital EDA**

**Import Required Libraries**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

Load Dataset

In [6]:
url = "https://raw.githubusercontent.com/madhubalaselvaraj25-cell/Customer-Banking-Financial-Analytics-Using-Python-and-Power-BI/refs/heads/main/Customer%20Banking%20Database_rawdata.csv"
df = pd.read_csv(url)

In [7]:
df.head()

,Customer ID,First Name,Last Name,Age,Gender,Address,City,Contact Number,Email,Account Type,...,Minimum Payment Due,Payment Due Date,Last Credit Card Payment Date,Rewards Points,Feedback ID,Feedback Date,Feedback Type,Resolution Status,Resolution Date,Anomaly
0,1,Joshua,Hall,45,Male,Address_1,Fort Worth,19458794854,joshua.hall@kag.com,Current,...,226.22,11/26/2023,3/20/2023,8142,1,10/6/2023,Suggestion,Resolved,1/22/2023,1
1,2,Mark,Taylor,47,Female,Address_2,Louisville,19458794855,mark.taylor@kag.com,Current,...,42.84,11/5/2023,6/16/2023,4306,2,4/7/2023,Complaint,Resolved,8/27/2023,1
2,3,Joseph,Flores,25,Female,Address_3,Philadelphia,19458794856,joseph.flores@kag.com,Current,...,162.12,1/8/2023,3/20/2023,4842,3,9/7/2023,Praise,Pending,5/11/2023,1
3,4,Kevin,Lee,52,Other,Address_4,Oklahoma City,19458794857,kevin.lee@kag.com,Savings,...,216.46,9/8/2023,10/15/2023,9463,4,5/28/2023,Complaint,Resolved,7/5/2023,1
4,5,Linda,Johnson,68,Other,Address_5,Phoenix,19458794858,linda.johnson@kag.com,Savings,...,1.29,3/4/2023,7/27/2023,2209,5,2/12/2023,Complaint,Resolved,11/21/2023,1

In [11]:
# Dataset Shape

df.shape

(5000, 40)

In [12]:
# Dataset information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 40 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer ID                        5000 non-null   int64
 1   First Name                         5000 non-null   object
 2   Last Name                          5000 non-null   object
 3   Age                                5000 non-null   int64
 4   Gender                             5000 non-null   object
 5   Address                            5000 non-null   object
 6   City                               5000 non-null   object
 7   Contact Number                     5000 non-null   int64
 8   Email                              5000 non-null   object
 9   Account Type                       5000 non-null   object
 10  Account Balance                    5000 non-null   float64
 11  Date Of Account Opening            5000 non-null   object
 12  Last Transaction Date              5000 non-null   object
 13  TransactionID                      5000 non-null   int64
 14  Transaction Date                   5000 non-null   object
 15  Transaction Type                   5000 non-null   object
 16  Transaction Amount                 5000 non-null   float64
 17  Account Balance After Transaction  5000 non-null   float64
 18  Branch ID                          5000 non-null   int64
 19  Loan ID                            5000 non-null   int64
 20  Loan Amount                        5000 non-null   float64
 21  Loan Type                          5000 non-null   object
 22  Interest Rate                      5000 non-null   float64
 23  Loan Term                          5000 non-null   int64
 24  Approval/Rejection Date            5000 non-null   object
 25  Loan Status                        5000 non-null   object
 26  CardID                             5000 non-null   int64
 27  Card Type                          5000 non-null   object
 28  Credit Limit                       5000 non-null   float64
 29  Credit Card Balance                5000 non-null   float64
 30  Minimum Payment Due                5000 non-null   float64
 31  Payment Due Date                   5000 non-null   object
 32  Last Credit Card Payment Date      5000 non-null   object
 33  Rewards Points                     5000 non-null   int64
 34  Feedback ID                        5000 non-null   int64
 35  Feedback Date                      5000 non-null   object
 36  Feedback Type                      5000 non-null   object
 37  Resolution Status                  5000 non-null   object
 38  Resolution Date                    5000 non-null   object
 39  Anomaly                            5000 non-null   int64
dtypes: float64(8), int64(11), object(21)
memory usage: 1.5+ MB

In [19]:
# Column Names

df.columns

Index(['Customer ID', 'First Name', 'Last Name', 'Age', 'Gender', 'Address',
       'City', 'Contact Number', 'Email', 'Account Type', 'Account Balance',
       'Date Of Account Opening', 'Last Transaction Date', 'TransactionID',
       'Transaction Date', 'Transaction Type', 'Transaction Amount',
       'Account Balance After Transaction', 'Branch ID', 'Loan ID',
       'Loan Amount', 'Loan Type', 'Interest Rate', 'Loan Term',
       'Approval/Rejection Date', 'Loan Status', 'CardID', 'Card Type',
       'Credit Limit', 'Credit Card Balance', 'Minimum Payment Due',
       'Payment Due Date', 'Last Credit Card Payment Date', 'Rewards Points',
       'Feedback ID', 'Feedback Date', 'Feedback Type', 'Resolution Status',
       'Resolution Date', 'Anomaly'],
      dtype='object')

In [14]:
# Statistical Summary

df.describe()

,Customer ID,Age,Contact Number,Account Balance,TransactionID,Transaction Amount,Account Balance After Transaction,Branch ID,Loan ID,Loan Amount,Interest Rate,Loan Term,CardID,Credit Limit,Credit Card Balance,Minimum Payment Due,Rewards Points,Feedback ID,Anomaly
count,5000.000000,5000.000000,5.000000e+03,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,43.469800,1.945880e+10,5060.570918,2500.500000,2508.501144,5037.418898,50.586800,2500.500000,25501.042806,5.505038,36.520800,2500.500000,5549.035830,2487.40084,124.370134,4966.161800,2500.500000,0.880000
std,1443.520003,15.145672,1.443520e+03,2849.356481,1443.520003,1450.194986,4053.220017,28.499539,1443.520003,14039.732628,2.629752,16.924315,1443.520003,2581.718105,1446.80295,72.340102,2901.410915,1443.520003,0.475021
min,1.000000,18.000000,1.945879e+10,107.200000,1.000000,10.570000,-4878.760000,1.000000,1.000000,1006.370000,1.000000,12.000000,1.000000,1007.000000,1.45000,0.070000,1.000000,1.000000,-1.000000
25%,1250.750000,30.000000,1.945880e+10,2582.777500,1250.750000,1241.150000,2047.205000,26.000000,1250.750000,13315.305000,3.200000,24.000000,1250.750000,3314.065000,1243.51750,62.180000,2475.250000,1250.750000,1.000000
50%,2500.500000,43.000000,1.945880e+10,5075.500000,2500.500000,2494.025000,5089.785000,50.000000,2500.500000,25909.705000,5.520000,36.000000,2500.500000,5567.485000,2461.62000,123.080000,4950.500000,2500.500000,1.000000
75%,3750.250000,57.000000,1.945880e+10,7509.760000,3750.250000,3796.222500,8036.367500,75.000000,3750.250000,37441.570000,7.832500,48.000000,3750.250000,7786.040000,3722.58000,186.125000,7483.250000,3750.250000,1.000000
max,5000.000000,69.000000,1.945880e+10,9998.110000,5000.000000,4998.390000,14911.380000,99.000000,5000.000000,49993.490000,10.000000,60.000000,5000.000000,9997.780000,4997.11000,249.860000,9999.000000,5000.000000,1.000000

In [16]:
# Check Missing Values

df.isnull().sum()

Customer ID                          0
First Name                           0
Last Name                            0
Age                                  0
Gender                               0
Address                              0
City                                 0
Contact Number                       0
Email                                0
Account Type                         0
Account Balance                      0
Date Of Account Opening              0
Last Transaction Date                0
TransactionID                        0
Transaction Date                     0
Transaction Type                     0
Transaction Amount                   0
Account Balance After Transaction    0
Branch ID                            0
Loan ID                              0
Loan Amount                          0
Loan Type                            0
Interest Rate                        0
Loan Term                            0
Approval/Rejection Date              0
Loan Status                          0
CardID                               0
Card Type                            0
Credit Limit                         0
Credit Card Balance                  0
Minimum Payment Due                  0
Payment Due Date                     0
Last Credit Card Payment Date        0
Rewards Points                       0
Feedback ID                          0
Feedback Date                        0
Feedback Type                        0
Resolution Status                    0
Resolution Date                      0
Anomaly                              0
dtype: int64

In [18]:
# Duplicate Record Check

df.duplicated().sum()

np.int64(0)

In [21]:
# Select the 15 Features for Analysis

selected_columns = ['Age','Gender',
                   'City','Account Type',
                   'Account Balance','Transaction Date',
                   'Transaction Type','Transaction Amount',
                   'Loan Type','Loan Amount','Loan Status',
                   'Card Type','Credit Card Balance',
                   'Feedback Type','Resolution Status']

In [24]:
df.analysis=df[selected_columns].copy()

df.analysis.head()

,Age,Gender,City,Account Type,Account Balance,Transaction Date,Transaction Type,Transaction Amount,Loan Type,Loan Amount,Loan Status,Card Type,Credit Card Balance,Feedback Type,Resolution Status
0,45,Male,Fort Worth,Current,1313.38,12/7/2023,Withdrawal,1457.61,Mortgage,32200.06,Rejected,AMEX,4524.32,Suggestion,Resolved
1,47,Female,Louisville,Current,5988.46,4/27/2023,Deposit,1660.99,Auto,47743.52,Approved,MasterCard,856.70,Complaint,Resolved
2,25,Female,Philadelphia,Current,8277.88,4/5/2023,Deposit,839.91,Auto,47981.31,Closed,AMEX,3242.36,Praise,Pending
3,52,Other,Oklahoma City,Savings,7487.21,7/28/2023,Withdrawal,4908.89,Personal,4482.80,Approved,MasterCard,4329.17,Complaint,Resolved
4,68,Other,Phoenix,Savings,6993.55,1/16/2023,Transfer,589.07,Mortgage,1092.33,Approved,Visa,25.72,Complaint,Resolved

In [27]:
# Check Selected Dataset Shape

df.analysis.shape

(5000, 15)

In [28]:
# Selected Dataset Information

df.analysis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  5000 non-null   int64
 1   Gender               5000 non-null   object
 2   City                 5000 non-null   object
 3   Account Type         5000 non-null   object
 4   Account Balance      5000 non-null   float64
 5   Transaction Date     5000 non-null   object
 6   Transaction Type     5000 non-null   object
 7   Transaction Amount   5000 non-null   float64
 8   Loan Type            5000 non-null   object
 9   Loan Amount          5000 non-null   float64
 10  Loan Status          5000 non-null   object
 11  Card Type            5000 non-null   object
 12  Credit Card Balance  5000 non-null   float64
 13  Feedback Type        5000 non-null   object
 14  Resolution Status    5000 non-null   object
dtypes: float64(4), int64(1), object(10)
memory usage: 586.1+ KB

In [30]:
# Statistical Summary of Selected Dataset

df.analysis.describe()

,Age,Account Balance,Transaction Amount,Loan Amount,Credit Card Balance
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000
mean,43.469800,5060.570918,2508.501144,25501.042806,2487.40084
std,15.145672,2849.356481,1450.194986,14039.732628,1446.80295
min,18.000000,107.200000,10.570000,1006.370000,1.45000
25%,30.000000,2582.777500,1241.150000,13315.305000,1243.51750
50%,43.000000,5075.500000,2494.025000,25909.705000,2461.62000
75%,57.000000,7509.760000,3796.222500,37441.570000,3722.58000
max,69.000000,9998.110000,4998.390000,49993.490000,4997.11000

In [31]:
# Statistical Summary of Selected Dataset

df.isnull().sum()

Customer ID                          0
First Name                           0
Last Name                            0
Age                                  0
Gender                               0
Address                              0
City                                 0
Contact Number                       0
Email                                0
Account Type                         0
Account Balance                      0
Date Of Account Opening              0
Last Transaction Date                0
TransactionID                        0
Transaction Date                     0
Transaction Type                     0
Transaction Amount                   0
Account Balance After Transaction    0
Branch ID                            0
Loan ID                              0
Loan Amount                          0
Loan Type                            0
Interest Rate                        0
Loan Term                            0
Approval/Rejection Date              0
Loan Status                          0
CardID                               0
Card Type                            0
Credit Limit                         0
Credit Card Balance                  0
Minimum Payment Due                  0
Payment Due Date                     0
Last Credit Card Payment Date        0
Rewards Points                       0
Feedback ID                          0
Feedback Date                        0
Feedback Type                        0
Resolution Status                    0
Resolution Date                      0
Anomaly                              0
dtype: int64

In [33]:
# Check Duplicate Records in Selected Dataset

df.analysis.duplicated().sum()

np.int64(0)